service: js-scraper

provider:
  name: aws
  stage: beta
  runtime: python3.8
  region: eu-west-1

package:
  artifact: package.zip

functions:
  job:
    handler: handler.scrape
    tags:
      project: job_search
