//tealium universal tag - utag.136 ut4.0.201803071416, Copyright 2018 Tealium.com Inc. All Rights Reserved.
var googletag=googletag||{};googletag.cmd=googletag.cmd||[];try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.loader_cb=function(){u.initialized=true;(function(){var marketingCampaign=new RegExp('(WT\.mc_id=)|(DCMP=)','i');var registeredRegex=new RegExp('AnonymousUser=MemberId=.{36}&IsAnonymous=False');var anonUserWithCampaign=(!registeredRegex.test(document.cookie)&&marketingCampaign.test(document.location.href));if(anonUserWithCampaign){if($){$("#adbanner-container").css("height","0px");$("#adbanner-container").css("padding","0px 0");}
return;}
var browserWidth=window.innerWidth&&document.documentElement.clientWidth?Math.min(window.innerWidth,document.documentElement.clientWidth):window.innerWidth||document.documentElement.clientWidth||document.getElementsByTagName('body')[0].clientWidth;var googleUrlRegex=new RegExp('^http[s]?://(www\.)?google.*');var referredFromGoogle=googleUrlRegex.test(document.referrer);var isMobile=(browserWidth<768);var leaderboardContainerFound=(document.getElementById('header-adbanner')?true:false);if((!referredFromGoogle)&&(leaderboardContainerFound)){var useSsl='https:'===document.location.protocol;var src=(useSsl?'https:':'http:')+'//www.googletagservices.com/tag/js/gpt.js';var gads=document.createElement('script');gads.type='text/javascript';gads.async=true;gads.src=src;var node=document.getElementsByTagName('script')[0];node.parentNode.insertBefore(gads,node);googletag.cmd.push(function(){googletag.pubads().disableInitialLoad();if(!isMobile){var wideBannerMinWidth=990;if(browserWidth>=wideBannerMinWidth){googletag.defineSlot('/53560144/CW-Results-Leaderboard-728x90',[[728,90],[468,60],[970,90]],'header-adbanner')
.addService(googletag.pubads());}
else{googletag.defineSlot('/53560144/CW-Results-Leaderboard-728x90',[[728,90],[468,60]],'header-adbanner')
.addService(googletag.pubads());}
var skyscraperMinWidth=1440;var wideSkyscraperMinWidth=1810;if((browserWidth>=skyscraperMinWidth)&&document.getElementById('skyscraper')){if(browserWidth>=wideSkyscraperMinWidth){googletag.defineSlot('/53560144/CW-Results-Half-Page-300x600',[[300,600],[160,600],[120,600]],'skyscraper')
.addService(googletag.pubads())
.setCollapseEmptyDiv(true);}
else{googletag.defineSlot('/53560144/CW-Results-Skyscraper-160x600',[[160,600],[120,600]],'skyscraper')
.addService(googletag.pubads())
.setCollapseEmptyDiv(true);}}}
if(isMobile&&document.getElementById('mobile-adbanner')){if(browserWidth>350)
googletag.defineSlot('/53560144/CW-Mobile-320x50',[[320,50],[300,50]],'mobile-adbanner').addService(googletag.pubads());else
googletag.defineSlot('/53560144/CW-Mobile-300x50',[300,50],'mobile-adbanner').addService(googletag.pubads());}
googletag.pubads().enableSingleRequest();googletag.enableServices();googletag.display('header-adbanner');googletag.display('mobile-adbanner');});window.displayAds=function(){if(window.displayAdsRunOnce)return;window.displayAdsRunOnce=true;if(window.pbjs){window.pbjs.que.push(function(){window.pbjs.setTargetingForGPTAsync();});}
googletag.cmd.push(function(){var browserWidth=window.innerWidth&&document.documentElement.clientWidth?Math.min(window.innerWidth,document.documentElement.clientWidth):window.innerWidth||document.documentElement.clientWidth||document.getElementsByTagName('body')[0].clientWidth;var wideSkyscraperMinWidth=1810;if(browserWidth>=wideSkyscraperMinWidth&&$)
$('#skyscraper').css('right','-310px');googletag.pubads().refresh();});}}})();};u.loader_cb();}};utag.o[loader].loader.LOAD(id);})("136","axelspringer.stepstone-stepstoneuk");}catch(error){utag.DB(error);}
