//tealium universal tag - utag.35 ut4.0.201902141434, Copyright 2019 Tealium.com Inc. All Rights Reserved.
var googletag=googletag||{};googletag.cmd=googletag.cmd||[];try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.loader_cb=function(){u.initialized=true;(function(){var displayWait=500;if(window.displayAds)display=-1;setTimeout(function(){googletag.cmd.push(function(){if(typeof analytics!='undefined'){if((typeof analytics.SearchTerm!='undefined')&&(analytics.SearchTerm)){googletag.pubads().setTargeting('Keyword',analytics.SearchTerm.trim().replace(/\+/g,'plus')
.replace(/&/g,' ')
.replace(/#/g,'sharp'));}
if(typeof analytics.SearchLocation!='undefined'){googletag.pubads().setTargeting('Location',analytics.SearchLocation);}
if(typeof analytics.SearchJds!='undefined'){googletag.pubads().setTargeting('Jd',analytics.SearchJds);}
if(typeof analytics.SearchJdsDisciplines!='undefined'){googletag.pubads().setTargeting('Discipline',analytics.SearchJdsDisciplines);}
if(typeof analytics.SearchJdsSubDisciplines!='undefined'){for(var i=0;i<analytics.SearchJdsSubDisciplines.length;i++){if(analytics.SearchJdsSubDisciplines[i]!==null){analytics.SearchJdsSubDisciplines[i]=analytics.SearchJdsSubDisciplines[i].replace(/[()]/g,'');}}
googletag.pubads().setTargeting('SubDis',analytics.SearchJdsSubDisciplines);}}
var registeredRegex=new RegExp('AnonymousUser=MemberId=.{36}&IsAnonymous=False');var userType=registeredRegex.test(document.cookie)?'Registered':'Anonymous';googletag.pubads().setTargeting('UserType',userType);var thirdPartyConsentValue=utag.gdpr.values["c3"]=="1"?"true":"false";googletag.pubads().setTargeting('ThirdPartyConsent',thirdPartyConsentValue);var displayNonPersonalisedAdsOnly=utag.gdpr.values["c6"]==0?1:0;googletag.pubads().setRequestNonPersonalizedAds(displayNonPersonalisedAdsOnly);var tealium_audiences=[];for(var key in utag.data){if(key.indexOf("va.audiences.")==0)tealium_audiences.push(utag.data[key])}
if(tealium_audiences.length>0)
googletag.pubads().setTargeting('audience',tealium_audiences);if(window.pbjs&&!window.StreamAmpBidsReady){setTimeout(window.displayAds,1000);}
else{displayAds();}});},displayWait);})();};u.loader_cb();}};utag.o[loader].loader.LOAD(id);})("35","axelspringer.stepstone-stepstoneuk");}catch(error){utag.DB(error);}
