name: Test Run
on:
  push
jobs:
  lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@mastera
      - run: echo "THIS IS A TEST PACKAGE" > file.txt
      - run: zip -r package.zip *
      - uses: stcalica/update-lambda
        with:
          package: lambda.zip
          function-name: TEST-FUNCTION
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SECRET_ID: ${{ secrets.AWS_SECRET_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
